name: CI/CD DemoDay

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv and tools
        run: |
          pip install --upgrade pip
          pip install uv ruff pytest

      - name: Install dependencies
        run: uv sync --no-cache

      - name: Lint with ruff
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q

  build-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t demo-day-app:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push image to Docker Hub
        run: |
          docker tag demo-day-app:latest ${{ secrets.DOCKER_USER }}/demo-day-app:latest
          docker push ${{ secrets.DOCKER_USER }}/demo-day-app:latest

  smoke-test:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run smoke test container
        run: |
          CONTAINER_ID=$(docker run --rm -d -p 8000:8080 ${{ secrets.DOCKER_USER }}/demo-day-app:latest)
          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
          echo "Aguardando app subir..."
          sleep 15
          pip install requests
          python .github/scripts/smoke_test.py

      - name: Stop container
        run: docker stop $CONTAINER_ID || true